### PR TITLE
Updated to babel 7

### PR DESCRIPTION
**Pull request by ghoshArnab**

### CODE REVIEW

**Comment by arcanis** [comment]
Hm ... what is this?

**Comment by ghoshArnab** [comment]
Hey, added a PR to update to latest babel version.

**Comment by arcanis** [comment]
Thanks, but I'm afraid I won't merge it. Infrastructure changes like this are usually better left to owners, if only because there's no way I review such lockfile changes 🙂

**Comment by ghoshArnab** [comment]
Will removing the lock file from the PR be fine?

**Comment by arcanis** [comment]
I mean, there has to be a point first .. why upgrade Babel at all? This module is very small, works fine in its current state, what makes it an imperative to upgrade Babel?

**Comment by ghoshArnab** [comment]
Babel 6 cli and core are failing npm audit due to security vulnerability due to dependent packages.
So, created the PR to fix that.

**Pull request closed without merging**
